/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Gaming Servers',
      items: ['game-servers/intro'],
    },
    {
      type: 'category',
      label: 'Virtual Private Servers',
      items: ['virtual-private-servers/intro'],
    },
    {
      type: 'category',
      label: 'Web Servers',
      items: ['web-servers/intro'],
    },
    {
      type: 'category',
      label: 'FAQ',
      items: ['faq/powerdown','faq/playerslots'],
    },
  ],

};

export default sidebars;
